name: Build PhysX 4.1 (macOS)

on:
  workflow_dispatch: 

jobs:
  build-physx-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout PhysX 4.1
      uses: actions/checkout@v4
      with:
        repository: BRUNOO1545/PhysX
        ref: 4.1
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Generate Projects (macOS)
      run: |
        cd physx
        chmod +x generate_projects.sh
        ./generate_projects.sh mac64

    - name: Compile macOS
      run: |
        cd physx/compiler/mac64
        
        echo "--- Compilando DEBUG ---"
        arch -x86_64 xcodebuild -project PhysXSDK.xcodeproj -configuration debug -target PhysXCharacterKinematic -target PhysXFoundation -target PhysXCommon -target PhysX -target PhysXCooking -target PhysXExtensions -target PhysXVehicle ARCHS=x86_64 ONLY_ACTIVE_ARCH=YES OTHER_CFLAGS="-Wno-error -Wno-missing-include-dirs" OTHER_CPLUSPLUSFLAGS="-Wno-error -Wno-missing-include-dirs"
        
        echo "--- Compilando RELEASE ---"
        arch -x86_64 xcodebuild -project PhysXSDK.xcodeproj -configuration release -target PhysXCharacterKinematic -target PhysXFoundation -target PhysXCommon -target PhysX -target PhysXCooking -target PhysXExtensions -target PhysXVehicle ARCHS=x86_64 ONLY_ACTIVE_ARCH=YES OTHER_CFLAGS="-Wno-error -Wno-missing-include-dirs" OTHER_CPLUSPLUSFLAGS="-Wno-error -Wno-missing-include-dirs"

    - name: Upload Binaries and Includes
      uses: actions/upload-artifact@v4
      with:
        name: PhysX-4.1-macOS-Binaries
        path: |
          physx/include/
          physx/bin/mac.x86_64/
